version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "okty-poc"
s3_bucket = "okty-poc-artifact"
region = "eu-west-3"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
