# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  poc-lambda

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  entrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/entrypoint.handle
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 3
      Role:
        Fn::GetAtt:
          - 'entrypointRole'
          - 'Arn'
      Description: Entrypoint of the builder
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  entrypointRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  nginxBuilder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/builders/nginx.handle
      FunctionName: okty-nginx
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 3
      Description: Nginx Builder

  phpBuilder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/builders/php.handle
      FunctionName: okty-php
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 3
      Description: PHP Builder

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
