name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: node:12
  
    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install 

    - name: Run Jest
      run: npm test 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        
    - name: Upload sources to artifact
      uses: actions/upload-artifact@v1
      with:
        name: sources
        path: ./
  
  deploy: 
    needs: build
    runs-on: ubuntu-18.04
    
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: source
          
      - name: List files
        run: ls
    
